name: test1
window_len: 5
n_extracts: 10
device: cuda:2
face_backbone: wide_resnet50_2
test_data_root: 
is_train: False
checkpoint: 
seed: 114514
batch_size: 4
num_workers: 0
confidence: 0.5
positional_encoding: True