batch_size: 32
device: cuda:0
epochs: 200
face_backbone: wide_resnet50_2
fix_backbone: true
is_train: true
lr: 1.0e-06
margin: 0.5
n_extracts: 10
name: self_supervised2
num_workers: 4
pos_neg_rate: 0.5
positional_encoding: true
pretrained_ckpt: /ljw/Main/CSL/weight/csl/self_supervised/ep63.pth
real_sample_only: true
seed: 114514
train_data_toot: /ljw/Main/PoseSync/datasets/train
val_data_root: /ljw/Main/PoseSync/datasets/train
val_gap: 5
window_len: 5
