name: train2
window_len: 5
n_extracts: 10
device: cuda:3
face_backbone: wide_resnet50_2
fix_backbone: True
train_data_toot: /ljw/Main/PoseSync/datasets/train
val_data_root: /ljw/Main/PoseSync/datasets/fake_dfdc
is_train: True
Contrastive_ckpt: /ljw/Main/CSL/weight/combine/train1/csl_ep5.pth
Temporal_ckpt: /ljw/Main/CSL/weight/combine/train1/tem_ep5.pth
Proj_ckpt: /ljw/Main/CSL/weight/combine/train1/proj_ep5.pth
lr: 1.0e-6
seed: 114514
batch_size: 28
num_workers: 4
epochs: 32
val_gap: 5
positional_encoding: True
scale_error: True
lr_schedluer: StepLR
fix_contrastive: True
fix_temporal: False
fix_proj: False
